name: Sanity checks
on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go version

      - name: Run tests
        run: go test

      - name: Format code
        run: go fmt ./...
